Assumptions:
1. 1 input sample
2. 3 features

In [1]:
import numpy as np

In [3]:
L0_size = 3
L1_size = 4
output_size = 1

In [42]:
X = np.random.randn(L0_size)
X = X.reshape(-1, 1)
X

array([[ 1.22495542],
       [-0.43886068],
       [ 0.18408065]])

In [15]:
# Initialize paramaters
W1 = np.random.rand(L1_size, L0_size)
b1 = np.random.rand(L1_size, 1)
W2 = np.random.rand(output_size, L1_size)
b2 = np.random.rand(output_size, 1)

print('W1: ', W1)
print('b1: ', b1)
print('W2: ', W2)
print('b2: ', b2)

W1:  [[0.14141755 0.23693666 0.21953128]
 [0.28512225 0.38717054 0.417407  ]
 [0.71236862 0.09460589 0.27094361]
 [0.8904505  0.00708969 0.92787579]]
b1:  [[0.04472023]
 [0.52058776]
 [0.23462053]
 [0.71643095]]
W2:  [[0.96169251 0.84883531 0.85594825 0.04809319]]
b2:  [[0.1761529]]


In [58]:
def tanh(Z):
    return np.tanh(Z)

In [66]:
def sigmoid(Z):
    return (1 / (1 + np.exp(-Z)))

### Forward Propagation

In [52]:
W1

array([[0.14141755, 0.23693666, 0.21953128],
       [0.28512225, 0.38717054, 0.417407  ],
       [0.71236862, 0.09460589, 0.27094361],
       [0.8904505 , 0.00708969, 0.92787579]])

In [53]:
X

array([[ 1.22495542],
       [-0.43886068],
       [ 0.18408065]])

In [63]:
Z1 = np.dot(W1, X) + b1
Z1

array([[0.1543797 ],
       [0.77677244],
       [1.11559701],
       [1.97488571]])

In [64]:
A1 = tanh(Z1)
A1

array([[0.15316483],
       [0.65085027],
       [0.80603196],
       [0.9622096 ]])

In [65]:
Z2 = np.dot(W2, A1) + b2
Z2

array([[1.61211244]])

In [67]:
A2 = sigmoid(Z2)
A2

array([[0.83370446]])